#!/bin/sh

xrdb -merge $HOME/.config/urxvt/themes/kaguya-dark &

# UIM input
export GTK_IM_MODULE='uim'
export QT_IM_MODULE='uim'
uim-xim &
export XMODIFIERS='@im=uim'

$HOME/.screenlayout/default.sh
xcompmgr &
unclutter &
setbg &
$HOME/.scripts/pump_color_changer.sh &
redshift -l 59.62:16.59 -t 6500K:3500K -b 1.0:0.6 &
